[workspace]

members = [
    "updatehub",
    "updatehub-package-schema",
    "updatehub-sdk",
    "updatehub-cloud-sdk",
]

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true
codegen-units = 1
panic = 'abort'
