[target.armv7-unknown-linux-gnueabihf]
image = "ossystems/rust-cross:armv7-unknown-linux-gnueabihf-libarchive-0.2.1d"

[target.aarch64-unknown-linux-gnu]
image = "ossystems/rust-cross:aarch64-unknown-linux-gnu-libarchive-0.2.1d"
