targets = [
        {triple = "x86_64-unknown-linux-gnu"},
        {triple = "armv7-unknown-linux-gnueabihf"},
]

[licenses]
unlicensed = "deny"
allow = [
    "Apache-2.0",
    "MIT",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "MPL-2.0",
    "Zlib",
]

[bans]
multiple-versions = "warn"
highlight = "all"
allow = []
deny = []
skip = [
     # Used only for building
     {name = "autocfg"}
]
