FORMAT: 1A

HOST: http://localhost:8080

# UpdateHub Agent local HTTP API routes

These are the routes available through HTTP on the device running the
UpdateHub Agent.


## Group Info

### info [GET /info]

Get general information.

Returns HTTP 200 and a json object as body. The object contains
the fields:
- version: the UpdateHub agent version
- config: a dump of the agent configuration
- firmware: a dump of the firmware metadata

+ Response 200 (application/json)

    + Body

            {
                "version": "0.1.0-87-ga836b13",

                "config": {
                    "polling": {
                        "enabled": true,
                        "interval": 3600,
                        "last-poll": "2017-01-01T00:00:00Z",
                        "first-poll": "2017-02-02T00:00:00Z",
                        "extra-interval": 300,
                        "retries": 1
                    },
                    "storage": {
                        "read-only": false
                    },
                    "update": {
                        "download-dir": "/tmp/download",
                        "auto-download-when-available": true,
                        "auto-install-after-download": true,
                        "auto-reboot-after-install": true,
                        "supported-install-modes": ["copy", "raw"]
                    },
                    "network": {
                        "server-address": "api.updatehub.io"
                    },
                    "firmware": {
                        "metadata-path": "/usr/share/updatehub"
                    }
                },

                "firmware": {
                    "product-uid": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
                    "device-identity": {
                        "id1": "value1",
                        "id2": "value2"
                    },
                    "device-attributes": {
                        "attr1": "value1",
                        "attr2": "value2",
                    },
                    "hardware": "board-name-revA",
                    "version": "1.2"
                }
            }






## Group Update

### probe [POST /probe]

Probe the server and download the update metadata if
available. Returns a json object containing the "update-available"
boolean field. It also may contain a "try-again-in" field which means
the caller should try the request again 'n' seconds from now, where
'n' is the value of "try-again-in".

This request accepts a "server-address" parameter on POST. When it's
present, it will use the address for the triggered probe (and the
update procedure too in case there is an update available).

If agent is busy (e.g. downloading a object or installing a object) the
returned http code is 202.

+ Attributes

    + "server-address": "http://different-address:8080" (string) - Server address which the update procedure will use for this request

+ Response 200 (application/json)

    + Body

            {
                "update-available": false,
                "try-again-in": 3600
            }

+ Response 202 (application/json)

    + Body

            {
                "busy": true,
                "current-state": "probe"
            }

### abort download [POST /update/download/abort]

Abort an update objects download (triggered by any command). On
success, returns HTTP 200 and a empty json object as body. On failure,
returns HTTP 400 and the error message inside a json object as body.

+ Response 200 (application/json)

    + Body

            {
                "message": "request accepted, download aborted"
            }

+ Response 400 (application/json)

    + Body

            {
                "error": "there is no download to be aborted"
            }






## Group Log

### log [GET /log]

Returns the agent log.

+ Response 200 (application/json)

    + Body

            [
                {
                    "level":"info",
                    "message":"info 1",
                    "time": "2017-06-29 13:59:31.831111065 -0300 -03",
                    "data": {}
                },
                {
                    "level":"info",
                    "message":"info 2",
                    "time": "2017-06-29 14:59:41.831111065 -0300 -03",
                    "data": {
                        "field1": "value1",
                        "field2": "value2"
                    }
                },
                {
                    "level":"error",
                    "message":"error n",
                    "time": "2017-06-29 15:59:51.831111065 -0300 -03",
                    "data": {}
                }
            ]
