name: CI - Linux - AArch64

on:
  push:
    branches:
      - master
      - v*
  pull_request:

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        name: [MSRV, stable, nightly]
        include:
          - name: MSRV
            version: 1.56.0
          - name: stable
            version: stable
          - name: nightly
            version: nightly

    name: Test ${{ matrix.name }} - aarch64-unknown-linux-gnu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install ${{ matrix.version }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.version }}
          target: aarch64-unknown-linux-gnu
          profile: minimal
          override: true
          default: true

      - name: Cache build contents
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.version }}-aarch64-unknown-linux-gnu-cargo-build-trimmed-${{ hashFiles('**/Cargo.lock') }}

      - name: Check build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: check
          args: --locked --target aarch64-unknown-linux-gnu --release --all --bins --examples --tests --all-features

      - name: Tests
        uses: actions-rs/cargo@v1
        timeout-minutes: 10
        with:
          use-cross: true
          command: test
          args: --locked --target aarch64-unknown-linux-gnu -p updatehub --release --all-features --no-fail-fast --lib -- --nocapture

      - name: Clear the cargo caches
        run: |
          cargo install cargo-cache --no-default-features --features ci-autoclean
          cargo-cache
