name: Code Style Check

on:
  push:
    branches:
      - master
      - v*
  pull_request:

jobs:
  check_format:
    name: Check Rust code style
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      
      - name: Install Rust ${{ matrix.toolchain }}
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }} && rustup component add rustfmt
      
      - name: Check format
        run: cargo fmt -- --check
